// ── THE MONSTRARIUM ──────────────────────────────────────────────
// Monstrarium of Representation — concepts, afflictions, passions, and
// the old myths, each given form as a full illustrated plate.
//
// STRUCTURE: the codex is divided into CHAPTERS (Caput I, II, III …).
// Each chapter opens with its own full-page illustrated cover plate,
// which always lands on the LEFT of a spread so it greets the reader
// as the chapter begins. The chapter's plates then follow, two per
// spread. Every plate is a complete illustration carrying its own
// title and lore, so the book renders each one full-bleed.
// ─────────────────────────────────────────────────────────────────

// Generic, count-agnostic front matter (shown on the opening page).
const FRONT_MATTER = {
  title: "Of Representation",
  // Latin echo from the cover banner: "the unknown is not the non-existent"
  motto: "Ignota non est inexistens",
  paragraphs: [
    "This codex gathers creatures that wear no single shape, for each is an idea made flesh — a fear, a vice, a turning of the mind, or an old god given form, name, and anatomy.",
    "It is ordered into chapters — the phobias and afflictions of the mind, the passions and sorrows of the heart, the vices and their answering virtues, and the myths of the Greeks, the Japanese, the Egyptians, the Norse, the peoples of India, and the Slavs. Each chapter opens with its own sign, and the studies that follow share its nature.",
    "However many leaves this book may hold, each is a study of something real but unseen. Turn them slowly. Look long, and do not mistake the drawing for the whole of the thing."
  ],
  foot: "Conceive the form. Let representation endure."
};

// Closing colophon (also generic).
const COLOPHON = {
  title: "Finis",
  paragraphs: [
    "Here the studies rest, though their subjects do not. They wait in mirrors and feast-halls, in still water and crowded thought, in temples and forests, in every quiet that follows feeling.",
    "What is named can be met. What is drawn can be understood. Close the book, and carry the knowing."
  ],
  foot: "Non quod verum est, sed quod apparere potest — hoc est monstrum."
};

// ── CHAPTERS ─────────────────────────────────────────────────────
// Each chapter has a divider/cover plate (assets/chapters/) and an
// ordered list of plates. The renderer (book.js) lays the divider on
// the LEFT page of a spread and flattens every plate into the legacy
// MONSTERS array the engine expects.
const CHAPTERS = [
  {
    caput: "I",
    title: "Phobias",
    slug: "phobia",
    divider: "assets/chapters/chapter-phobia.webp",
    monsters: [
      { id: "phobia-ablutophobia", name: "Ablutophobia", file: "phobia-ablutophobia.webp" },
      { id: "phobia-acrophobia", name: "Acrophobia", file: "phobia-acrophobia.webp" },
      { id: "phobia-aerophobia", name: "Aerophobia", file: "phobia-aerophobia.webp" },
      { id: "phobia-agoraphobia", name: "Agoraphobia", file: "phobia-agoraphobia.webp" },
      { id: "phobia-apeirophobia", name: "Apeirophobia", file: "phobia-apeirophobia.webp" },
      { id: "phobia-aracnophobia", name: "Aracnophobia", file: "phobia-aracnophobia.webp" },
      { id: "phobia-arithmophobia", name: "Arithmophobia", file: "phobia-arithmophobia.webp" },
      { id: "phobia-astraphobia", name: "Astraphobia", file: "phobia-astraphobia.webp" },
      { id: "phobia-athazagoraphobia", name: "Athazagoraphobia", file: "phobia-athazagoraphobia.webp" },
      { id: "phobia-bathophobia", name: "Bathophobia", file: "phobia-bathophobia.webp" },
      { id: "phobia-cherophobia", name: "Cherophobia", file: "phobia-cherophobia.webp" },
      { id: "phobia-claustrophobia", name: "Claustrophobia", file: "phobia-claustrophobia.webp" },
      { id: "phobia-coulrophobia", name: "Coulrophobia", file: "phobia-coulrophobia.webp" },
      { id: "phobia-cynophobia", name: "Cynophobia", file: "phobia-cynophobia.webp" },
      { id: "phobia-decidophobia", name: "Decidophobia", file: "phobia-decidophobia.webp" },
      { id: "phobia-eisoptrophobia", name: "Eisoptrophobia", file: "phobia-eisoptrophobia.webp" },
      { id: "phobia-emetophobia", name: "Emetophobia", file: "phobia-emetophobia.webp" },
      { id: "phobia-entomophobia", name: "Entomophobia", file: "phobia-entomophobia.webp" },
      { id: "phobia-ergophobia", name: "Ergophobia", file: "phobia-ergophobia.webp" },
      { id: "phobia-glossophobia", name: "Glossophobia", file: "phobia-glossophobia.webp" },
      { id: "phobia-hemophobia", name: "Hemophobia", file: "phobia-hemophobia.webp" },
      { id: "phobia-hexakosioihexekontahexaphobia", name: "Hexakosioihexekontahexaphobia", file: "phobia-hexakosioihexekontahexaphobia.webp" },
      { id: "phobia-hippopotomonstrosesquippedaliophobia", name: "Hippopotomonstrosesquippedaliophobia", file: "phobia-hippopotomonstrosesquippedaliophobia.webp" },
      { id: "phobia-linonophobia", name: "Linonophobia", file: "phobia-linonophobia.webp" },
      { id: "phobia-megalophobia", name: "Megalophobia", file: "phobia-megalophobia.webp" },
      { id: "phobia-mysophobia", name: "Mysophobia", file: "phobia-mysophobia.webp" },
      { id: "phobia-necrophobia", name: "Necrophobia", file: "phobia-necrophobia.webp" },
      { id: "phobia-nuctophobia", name: "Nuctophobia", file: "phobia-nuctophobia.webp" },
      { id: "phobia-ophidiophobia", name: "Ophidiophobia", file: "phobia-ophidiophobia.webp" },
      { id: "phobia-optophobia", name: "Optophobia", file: "phobia-optophobia.webp" },
      { id: "phobia-phobophobia", name: "Phobophobia", file: "phobia-phobophobia.webp" },
      { id: "phobia-plutophobia", name: "Plutophobia", file: "phobia-plutophobia.webp" },
      { id: "phobia-pogonophobia", name: "Pogonophobia", file: "phobia-pogonophobia.webp" },
      { id: "phobia-pyrophobia", name: "Pyrophobia", file: "phobia-pyrophobia.webp" },
      { id: "phobia-somniphobia", name: "Somniphobia", file: "phobia-somniphobia.webp" },
      { id: "phobia-technophobia", name: "Technophobia", file: "phobia-technophobia.webp" },
      { id: "phobia-thanatophobia", name: "Thanatophobia", file: "phobia-thanatophobia.webp" },
      { id: "phobia-tripophobia", name: "Tripophobia", file: "phobia-tripophobia.webp" },
      { id: "phobia-trypanophobia", name: "Trypanophobia", file: "phobia-trypanophobia.webp" },
      { id: "phobia-xenophobia", name: "Xenophobia", file: "phobia-xenophobia.webp" },
    ]
  },
  {
    caput: "II",
    title: "Afflictions",
    slug: "afflictions",
    divider: "assets/chapters/chapter-afflictions.webp",
    monsters: [
      { id: "afflictions-adhd", name: "ADHD", file: "afflictions-adhd.webp" },
      { id: "afflictions-anorexia", name: "Anorexia", file: "afflictions-anorexia.webp" },
      { id: "afflictions-anxiety", name: "Anxiety", file: "afflictions-anxiety.webp" },
      { id: "afflictions-bipolardisorder", name: "Bipolar Disorder", file: "afflictions-bipolardisorder.webp" },
      { id: "afflictions-bruxism", name: "Bruxism", file: "afflictions-bruxism.webp" },
      { id: "afflictions-bulimia", name: "Bulimia", file: "afflictions-bulimia.webp" },
      { id: "afflictions-catatonia", name: "Catatonia", file: "afflictions-catatonia.webp" },
      { id: "afflictions-depression", name: "Depression", file: "afflictions-depression.webp" },
      { id: "afflictions-dermatillomania", name: "Dermatillomania", file: "afflictions-dermatillomania.webp" },
      { id: "afflictions-dysthymia", name: "Dysthymia", file: "afflictions-dysthymia.webp" },
      { id: "afflictions-hoarding-disorder", name: "Hoarding Disorder", file: "afflictions-hoarding-disorder.webp" },
      { id: "afflictions-hypochondria", name: "Hypochondria", file: "afflictions-hypochondria.webp" },
      { id: "afflictions-insomnia", name: "Insomnia", file: "afflictions-insomnia.webp" },
      { id: "afflictions-kleptomania", name: "Kleptomania", file: "afflictions-kleptomania.webp" },
      { id: "afflictions-mania", name: "Mania", file: "afflictions-mania.webp" },
      { id: "afflictions-misokinesia", name: "Misokinesia", file: "afflictions-misokinesia.webp" },
      { id: "afflictions-narcolepsy", name: "Narcolepsy", file: "afflictions-narcolepsy.webp" },
      { id: "afflictions-ocd", name: "OCD", file: "afflictions-ocd.webp" },
      { id: "afflictions-onychophagia", name: "Onychophagia", file: "afflictions-onychophagia.webp" },
      { id: "afflictions-orthorexia", name: "Orthorexia", file: "afflictions-orthorexia.webp" },
      { id: "afflictions-panic-disorder", name: "Panic Disorder", file: "afflictions-panic-disorder.webp" },
      { id: "afflictions-paranoia", name: "Paranoia", file: "afflictions-paranoia.webp" },
      { id: "afflictions-pica", name: "Pica", file: "afflictions-pica.webp" },
      { id: "afflictions-ptsd", name: "PTSD", file: "afflictions-ptsd.webp" },
      { id: "afflictions-pyromania", name: "Pyromania", file: "afflictions-pyromania.webp" },
      { id: "afflictions-restless-legs-syndrome", name: "Restless Legs Syndrome", file: "afflictions-restless-legs-syndrome.webp" },
      { id: "afflictions-schizoprenia", name: "Schizophrenia", file: "afflictions-schizoprenia.webp" },
      { id: "afflictions-seasonal-affective-disorder", name: "Seasonal Affective Disorder", file: "afflictions-seasonal-affective-disorder.webp" },
      { id: "afflictions-selective-mutism", name: "Selective Mutism", file: "afflictions-selective-mutism.webp" },
      { id: "afflictions-somatization", name: "Somatization", file: "afflictions-somatization.webp" },
      { id: "afflictions-trichotillomania", name: "Trichotillomania", file: "afflictions-trichotillomania.webp" },
      { id: "afflictions-vitiligo", name: "Vitiligo", file: "afflictions-vitiligo.webp" },
    ]
  },
  {
    caput: "III",
    title: "Delusions & Disorders",
    slug: "delusions",
    divider: "assets/chapters/chapter-delusions.webp",
    monsters: [
      { id: "delusions-adele-syndrome", name: "Adele Syndrome", file: "delusions-adele-syndrome.webp" },
      { id: "delusions-alice-in-wonderland-syndrome", name: "Alice In Wonderland Syndrome", file: "delusions-alice-in-wonderland-syndrome.webp" },
      { id: "delusions-aliendhandsyndrome", name: "Alien Hand Syndrome", file: "delusions-aliendhandsyndrome.webp" },
      { id: "delusions-anton-syndrome", name: "Anton Syndrome", file: "delusions-anton-syndrome.webp" },
      { id: "delusions-aspergers-syndrome", name: "Asperger's Syndrome", file: "delusions-aspergers-syndrome.webp" },
      { id: "delusions-bad-trip", name: "Bad Trip", file: "delusions-bad-trip.webp" },
      { id: "delusions-body-dismorphia", name: "Body Dysmorphia", file: "delusions-body-dismorphia.webp" },
      { id: "delusions-body-integrity-dysphoria", name: "Body Integrity Dysphoria", file: "delusions-body-integrity-dysphoria.webp" },
      { id: "delusions-borderline", name: "Borderline", file: "delusions-borderline.webp" },
      { id: "delusions-bradypsychia", name: "Bradypsychia", file: "delusions-bradypsychia.webp" },
      { id: "delusions-burnout-syndrome", name: "Burnout Syndrome", file: "delusions-burnout-syndrome.webp" },
      { id: "delusions-capgras-syndrome", name: "Capgras Syndrome", file: "delusions-capgras-syndrome.webp" },
      { id: "delusions-charles-bonnet-syndrome", name: "Charles Bonnet Syndrome", file: "delusions-charles-bonnet-syndrome.webp" },
      { id: "delusions-clinical-lycanthropy", name: "Clinical Lycanthropy", file: "delusions-clinical-lycanthropy.webp" },
      { id: "delusions-cotards-syndrome", name: "Cotard's Syndrome", file: "delusions-cotards-syndrome.webp" },
      { id: "delusions-depersonalisation", name: "Depersonalisation", file: "delusions-depersonalisation.webp" },
      { id: "delusions-depersonalization-derealization-disorder", name: "Depersonalization Derealization Disorder", file: "delusions-depersonalization-derealization-disorder.webp" },
      { id: "delusions-dissociative-identity-disorder", name: "Dissociative Identity Disorder", file: "delusions-dissociative-identity-disorder.webp" },
      { id: "delusions-dunning-kruger-effect", name: "Dunning-Kruger Effect", file: "delusions-dunning-kruger-effect.webp" },
      { id: "delusions-erotomania", name: "Erotomania", file: "delusions-erotomania.webp" },
      { id: "delusions-folie-a-deux", name: "Folie à Deux", file: "delusions-folie-a-deux.webp" },
      { id: "delusions-fregulidelusion", name: "Fregoli Delusion", file: "delusions-fregulidelusion.webp" },
      { id: "delusions-hypnagogia", name: "Hypnagogia", file: "delusions-hypnagogia.webp" },
      { id: "delusions-hypnic-jerks", name: "Hypnic Jerks", file: "delusions-hypnic-jerks.webp" },
      { id: "delusions-jamais-vu", name: "Jamais Vu", file: "delusions-jamais-vu.webp" },
      { id: "delusions-jerusalem-syndrome", name: "Jerusalem Syndrome", file: "delusions-jerusalem-syndrome.webp" },
      { id: "delusions-lucid-dream", name: "Lucid Dream", file: "delusions-lucid-dream.webp" },
      { id: "delusions-misophonia", name: "Misophonia", file: "delusions-misophonia.webp" },
      { id: "delusions-munchausen-syndrome", name: "Münchausen Syndrome", file: "delusions-munchausen-syndrome.webp" },
      { id: "delusions-out-of-body-experience", name: "Out of Body Experience", file: "delusions-out-of-body-experience.webp" },
      { id: "delusions-pareidolia", name: "Pareidolia", file: "delusions-pareidolia.webp" },
      { id: "delusions-persecutory-delusion", name: "Persecutory Delusion", file: "delusions-persecutory-delusion.webp" },
      { id: "delusions-peter-pan-syndrome", name: "Peter Pan Syndrome", file: "delusions-peter-pan-syndrome.webp" },
      { id: "delusions-savant-syndrome", name: "Savant Syndrome", file: "delusions-savant-syndrome.webp" },
      { id: "delusions-schizoaffective-disorder", name: "Schizoaffective Disorder", file: "delusions-schizoaffective-disorder.webp" },
      { id: "delusions-sleep-paralysis", name: "Sleep Paralysis", file: "delusions-sleep-paralysis.webp" },
      { id: "delusions-somatoparaphrenia", name: "Somatoparaphrenia", file: "delusions-somatoparaphrenia.webp" },
      { id: "delusions-somnambulon", name: "Somnambulon", file: "delusions-somnambulon.webp" },
      { id: "delusions-stockholm-syndrome", name: "Stockholm Syndrome", file: "delusions-stockholm-syndrome.webp" },
      { id: "delusions-synesthesia", name: "Synesthesia", file: "delusions-synesthesia.webp" },
      { id: "delusions-tachypsychia", name: "Tachypsychia", file: "delusions-tachypsychia.webp" },
      { id: "delusions-time-dilation", name: "Time Dilation", file: "delusions-time-dilation.webp" },
      { id: "delusions-tom-jerry-syndrome", name: "Tom & Jerry Syndrome", file: "delusions-tom-jerry-syndrome.webp" },
      { id: "delusions-tourette", name: "Tourette", file: "delusions-tourette.webp" },
      { id: "delusions-truman-show-delusion", name: "Truman Show Delusion", file: "delusions-truman-show-delusion.webp" },
      { id: "delusions-visual-snow-syndrome", name: "Visual Snow Syndrome", file: "delusions-visual-snow-syndrome.webp" },
    ]
  },
  {
    caput: "IV",
    title: "Passions",
    slug: "passions",
    divider: "assets/chapters/chapter-passions.webp",
    monsters: [
      { id: "passions-addiction", name: "Addiction", file: "passions-addiction.webp" },
      { id: "passions-ambition", name: "Ambition", file: "passions-ambition.webp" },
      { id: "passions-desire", name: "Desire", file: "passions-desire.webp" },
      { id: "passions-devotion", name: "Devotion", file: "passions-devotion.webp" },
      { id: "passions-ecstasy", name: "Ecstasy", file: "passions-ecstasy.webp" },
      { id: "passions-ecstatic-release", name: "Ecstatic Release", file: "passions-ecstatic-release.webp" },
      { id: "passions-elation", name: "Elation", file: "passions-elation.webp" },
      { id: "passions-euphoria", name: "Euphoria", file: "passions-euphoria.webp" },
      { id: "passions-fanaticism", name: "Fanaticism", file: "passions-fanaticism.webp" },
      { id: "passions-fervor", name: "Fervor", file: "passions-fervor.webp" },
      { id: "passions-forelsket", name: "Forelsket", file: "passions-forelsket.webp" },
      { id: "passions-fury", name: "Fury", file: "passions-fury.webp" },
      { id: "passions-hate", name: "Hate", file: "passions-hate.webp" },
      { id: "passions-infatuation", name: "Infatuation", file: "passions-infatuation.webp" },
      { id: "passions-jealousy", name: "Jealousy", file: "passions-jealousy.webp" },
      { id: "passions-kamasutra", name: "Kamasutra", file: "passions-kamasutra.webp" },
      { id: "passions-longing", name: "Longing", file: "passions-longing.webp" },
      { id: "passions-love", name: "Love", file: "passions-love.webp" },
      { id: "passions-lust-passion", name: "Lust (the passion)", file: "passions-lust-passion.webp" },
      { id: "passions-obsession", name: "Obsession", file: "passions-obsession.webp" },
      { id: "passions-onsra", name: "Onsra", file: "passions-onsra.webp" },
      { id: "passions-passion", name: "Passion", file: "passions-passion.webp" },
      { id: "passions-pride-passion", name: "Pride (the passion)", file: "passions-pride-passion.webp" },
      { id: "passions-rapture", name: "Rapture", file: "passions-rapture.webp" },
      { id: "passions-selenophilia", name: "Selenophilia", file: "passions-selenophilia.webp" },
      { id: "passions-temptation", name: "Temptation", file: "passions-temptation.webp" },
      { id: "passions-thrill", name: "Thrill", file: "passions-thrill.webp" },
      { id: "passions-vengeance", name: "Vengeance", file: "passions-vengeance.webp" },
      { id: "passions-wanderlust", name: "Wanderlust", file: "passions-wanderlust.webp" },
      { id: "passions-wrath-passion", name: "Wrath-Passion", file: "passions-wrath-passion.webp" },
      { id: "passions-yearning", name: "Yearning", file: "passions-yearning.webp" },
      { id: "passions-zeal", name: "Zeal", file: "passions-zeal.webp" },
    ]
  },
  {
    caput: "V",
    title: "Sorrows",
    slug: "sorrows",
    divider: "assets/chapters/chapter-sorrows.webp",
    monsters: [
      { id: "sorrows-abandonment", name: "Abandonment", file: "sorrows-abandonment.webp" },
      { id: "sorrows-anguish", name: "Anguish", file: "sorrows-anguish.webp" },
      { id: "sorrows-apathy", name: "Apathy", file: "sorrows-apathy.webp" },
      { id: "sorrows-bitterness", name: "Bitterness", file: "sorrows-bitterness.webp" },
      { id: "sorrows-dematerialisation", name: "Dematerialisation", file: "sorrows-dematerialisation.webp" },
      { id: "sorrows-despair", name: "Despair", file: "sorrows-despair.webp" },
      { id: "sorrows-disappointment", name: "Disappointment", file: "sorrows-disappointment.webp" },
      { id: "sorrows-disillusionment", name: "Disillusionment", file: "sorrows-disillusionment.webp" },
      { id: "sorrows-emptiness", name: "Emptiness", file: "sorrows-emptiness.webp" },
      { id: "sorrows-fernweh", name: "Fernweh", file: "sorrows-fernweh.webp" },
      { id: "sorrows-fragility", name: "Fragility", file: "sorrows-fragility.webp" },
      { id: "sorrows-grief", name: "Grief", file: "sorrows-grief.webp" },
      { id: "sorrows-grief-eternal", name: "Grief Eternal", file: "sorrows-grief-eternal.webp" },
      { id: "sorrows-guilt", name: "Guilt", file: "sorrows-guilt.webp" },
      { id: "sorrows-heartbreak", name: "Heartbreak", file: "sorrows-heartbreak.webp" },
      { id: "sorrows-helplessness", name: "Helplessness", file: "sorrows-helplessness.webp" },
      { id: "sorrows-hiraeth", name: "Hiraeth", file: "sorrows-hiraeth.webp" },
      { id: "sorrows-homesickness", name: "Homesickness", file: "sorrows-homesickness.webp" },
      { id: "sorrows-hopelessness", name: "Hopelessness", file: "sorrows-hopelessness.webp" },
      { id: "sorrows-loneliness", name: "Loneliness", file: "sorrows-loneliness.webp" },
      { id: "sorrows-longing-sorrow", name: "Longing-Sorrow", file: "sorrows-longing-sorrow.webp" },
      { id: "sorrows-melancholy", name: "Melancholy", file: "sorrows-melancholy.webp" },
      { id: "sorrows-mono-no-aware", name: "Mono no aware", file: "sorrows-mono-no-aware.webp" },
      { id: "sorrows-mourning", name: "Mourning", file: "sorrows-mourning.webp" },
      { id: "sorrows-nostalgia", name: "Nostalgia", file: "sorrows-nostalgia.webp" },
      { id: "sorrows-numbness", name: "Numbness", file: "sorrows-numbness.webp" },
      { id: "sorrows-quiet-sorrow", name: "Quiet Sorrow", file: "sorrows-quiet-sorrow.webp" },
      { id: "sorrows-regret", name: "Regret", file: "sorrows-regret.webp" },
      { id: "sorrows-remorse", name: "Remorse", file: "sorrows-remorse.webp" },
      { id: "sorrows-saudade", name: "Saudade", file: "sorrows-saudade.webp" },
      { id: "sorrows-sorrow", name: "Sorrow", file: "sorrows-sorrow.webp" },
      { id: "sorrows-weltschmerz", name: "Weltschmerz", file: "sorrows-weltschmerz.webp" },
      { id: "sorrows-wistfulness", name: "Wistfulness", file: "sorrows-wistfulness.webp" },
      { id: "sorrows-yearning-sorrow", name: "Yearning-Sorrow", file: "sorrows-yearning-sorrow.webp" },
    ]
  },
  {
    caput: "VI",
    title: "The Self",
    slug: "self",
    divider: "assets/chapters/chapter-self.webp",
    monsters: [
      { id: "self-acceptance", name: "Acceptance", file: "self-acceptance.webp" },
      { id: "self-awakening", name: "Awakening", file: "self-awakening.webp" },
      { id: "self-becoming", name: "Becoming", file: "self-becoming.webp" },
      { id: "self-conscience", name: "Conscience", file: "self-conscience.webp" },
      { id: "self-curiosity", name: "Curiosity", file: "self-curiosity.webp" },
      { id: "self-detachment", name: "Detachment", file: "self-detachment.webp" },
      { id: "self-doubt", name: "Doubt", file: "self-doubt.webp" },
      { id: "self-deja-vu", name: "Déjà Vu", file: "self-deja-vu.webp" },
      { id: "self-ego", name: "Ego", file: "self-ego.webp" },
      { id: "self-fata-morgana", name: "Fata Morgana", file: "self-fata-morgana.webp" },
      { id: "self-flashbacks", name: "Flashbacks", file: "self-flashbacks.webp" },
      { id: "self-identity", name: "Identity", file: "self-identity.webp" },
      { id: "self-ikigai", name: "Ikigai", file: "self-ikigai.webp" },
      { id: "self-inner-child", name: "Inner Child", file: "self-inner-child.webp" },
      { id: "self-intuition", name: "Intuition", file: "self-intuition.webp" },
      { id: "self-memory", name: "Memory", file: "self-memory.webp" },
      { id: "self-mortality", name: "Mortality", file: "self-mortality.webp" },
      { id: "self-overdosis", name: "Overdose", file: "self-overdosis.webp" },
      { id: "self-persona", name: "Persona", file: "self-persona.webp" },
      { id: "self-pride-of-self", name: "Pride of Self", file: "self-pride-of-self.webp" },
      { id: "self-psychosis", name: "Psychosis", file: "self-psychosis.webp" },
      { id: "self-reflection", name: "Reflection", file: "self-reflection.webp" },
      { id: "self-shadow-self", name: "Shadow Self", file: "self-shadow-self.webp" },
      { id: "self-shame", name: "Shame", file: "self-shame.webp" },
      { id: "self-solitude", name: "Solitude", file: "self-solitude.webp" },
      { id: "self-sonder", name: "Sonder", file: "self-sonder.webp" },
      { id: "self-soul", name: "Soul", file: "self-soul.webp" },
      { id: "self-suicide", name: "Suicide", file: "self-suicide.webp" },
      { id: "self-transformation", name: "Transformation", file: "self-transformation.webp" },
    ]
  },
  {
    caput: "VII",
    title: "Vices",
    slug: "vices",
    divider: "assets/chapters/chapter-vices.webp",
    monsters: [
      { id: "vices-acedia", name: "Acedia", file: "vices-acedia.webp" },
      { id: "vices-arrogance", name: "Arrogance", file: "vices-arrogance.webp" },
      { id: "vices-betrayal", name: "Betrayal", file: "vices-betrayal.webp" },
      { id: "vices-cowardice", name: "Cowardice", file: "vices-cowardice.webp" },
      { id: "vices-cruelty", name: "Cruelty", file: "vices-cruelty.webp" },
      { id: "vices-deceit", name: "Deceit", file: "vices-deceit.webp" },
      { id: "vices-despair-vice", name: "Despair (as vice)", file: "vices-despair-vice.webp" },
      { id: "vices-dishonesty", name: "Dishonesty", file: "vices-dishonesty.webp" },
      { id: "vices-envy", name: "Envy", file: "vices-envy.webp" },
      { id: "vices-gluttony", name: "Gluttony", file: "vices-gluttony.webp" },
      { id: "vices-greed", name: "Greed", file: "vices-greed.webp" },
      { id: "vices-hypocrisy", name: "Hypocrisy", file: "vices-hypocrisy.webp" },
      { id: "vices-indolence", name: "Indolence", file: "vices-indolence.webp" },
      { id: "vices-ingratitude", name: "Ingratitude", file: "vices-ingratitude.webp" },
      { id: "vices-lust", name: "Lust", file: "vices-lust.webp" },
      { id: "vices-malice", name: "Malice", file: "vices-malice.webp" },
      { id: "vices-pride", name: "Pride", file: "vices-pride.webp" },
      { id: "vices-resentment", name: "Resentment", file: "vices-resentment.webp" },
      { id: "vices-self-sabotage", name: "Self-Sabotage", file: "vices-self-sabotage.webp" },
      { id: "vices-selfishness", name: "Selfishness", file: "vices-selfishness.webp" },
      { id: "vices-sloth", name: "Sloth", file: "vices-sloth.webp" },
      { id: "vices-spite", name: "Spite", file: "vices-spite.webp" },
      { id: "vices-tyranny", name: "Tyranny", file: "vices-tyranny.webp" },
      { id: "vices-wickedness", name: "Wickedness", file: "vices-wickedness.webp" },
      { id: "vices-wrath", name: "Wrath", file: "vices-wrath.webp" },
    ]
  },
  {
    caput: "VIII",
    title: "Virtues",
    slug: "virtues",
    divider: "assets/chapters/chapter-virtues.webp",
    monsters: [
      { id: "virtues-abstinence", name: "Abstinence", file: "virtues-abstinence.webp" },
      { id: "virtues-chastity", name: "Chastity", file: "virtues-chastity.webp" },
      { id: "virtues-diligence", name: "Diligence", file: "virtues-diligence.webp" },
      { id: "virtues-empathy", name: "Empathy", file: "virtues-empathy.webp" },
      { id: "virtues-generosity", name: "Generosity", file: "virtues-generosity.webp" },
      { id: "virtues-honor", name: "Honor", file: "virtues-honor.webp" },
      { id: "virtues-humility", name: "Humility", file: "virtues-humility.webp" },
      { id: "virtues-kindness", name: "Kindness", file: "virtues-kindness.webp" },
      { id: "virtues-kintsugi", name: "Kintsugi", file: "virtues-kintsugi.webp" },
      { id: "virtues-patience", name: "Patience", file: "virtues-patience.webp" },
      { id: "virtues-temperance", name: "Temperance", file: "virtues-temperance.webp" },
      { id: "virtues-versatility", name: "Versatility", file: "virtues-versatility.webp" },
      { id: "virtues-willpower", name: "Willpower", file: "virtues-willpower.webp" },
    ]
  },
  {
    caput: "IX",
    title: "Greek Mythology",
    slug: "greek",
    divider: "assets/chapters/chapter-greek.webp",
    monsters: [
      { id: "greek-aphrodite", name: "Aphrodite", file: "greek-aphrodite.webp" },
      { id: "greek-apollo", name: "Apollo", file: "greek-apollo.webp" },
      { id: "greek-artemis", name: "Artemis", file: "greek-artemis.webp" },
      { id: "greek-athena", name: "Athena", file: "greek-athena.webp" },
      { id: "greek-cronus", name: "Cronus", file: "greek-cronus.webp" },
      { id: "greek-demeter", name: "Demeter", file: "greek-demeter.webp" },
      { id: "greek-dionysus", name: "Dionysus", file: "greek-dionysus.webp" },
      { id: "greek-eros", name: "Eros", file: "greek-eros.webp" },
      { id: "greek-gaia", name: "Gaia", file: "greek-gaia.webp" },
      { id: "greek-hades", name: "Hades", file: "greek-hades.webp" },
      { id: "greek-hecate", name: "Hecate", file: "greek-hecate.webp" },
      { id: "greek-helios", name: "Helios", file: "greek-helios.webp" },
      { id: "greek-hephaestus", name: "Hephaestus", file: "greek-hephaestus.webp" },
      { id: "greek-hera", name: "Hera", file: "greek-hera.webp" },
      { id: "greek-hermes", name: "Hermes", file: "greek-hermes.webp" },
      { id: "greek-nyx", name: "Nyx", file: "greek-nyx.webp" },
      { id: "greek-pan", name: "Pan", file: "greek-pan.webp" },
      { id: "greek-persephone", name: "Persephone", file: "greek-persephone.webp" },
      { id: "greek-poseidon", name: "Poseidon", file: "greek-poseidon.webp" },
      { id: "greek-zeus", name: "Zeus", file: "greek-zeus.webp" },
      { id: "greek-centaur", name: "Centaur", file: "greek-centaur.webp" },
      { id: "greek-cerberus", name: "Cerberus", file: "greek-cerberus.webp" },
      { id: "greek-chimera", name: "Chimera", file: "greek-chimera.webp" },
      { id: "greek-cyclops", name: "Cyclops", file: "greek-cyclops.webp" },
      { id: "greek-harpies", name: "Harpies", file: "greek-harpies.webp" },
      { id: "greek-hecatoncheires", name: "Hecatoncheires", file: "greek-hecatoncheires.webp" },
      { id: "greek-hydra", name: "Hydra", file: "greek-hydra.webp" },
      { id: "greek-medusa", name: "Medusa", file: "greek-medusa.webp" },
      { id: "greek-minotaur", name: "Minotaur", file: "greek-minotaur.webp" },
      { id: "greek-pegasus", name: "Pegasus", file: "greek-pegasus.webp" },
      { id: "greek-typhon", name: "Typhon", file: "greek-typhon.webp" },
    ]
  },
  {
    caput: "X",
    title: "Japanese Yokai",
    slug: "japanese",
    divider: "assets/chapters/chapter-japanese.webp",
    monsters: [
      { id: "japanese-abumiguchi", name: "Abumiguchi", file: "japanese-abumiguchi.webp" },
      { id: "japanese-abura-sumashi", name: "Abura-Sumashi", file: "japanese-abura-sumashi.webp" },
      { id: "japanese-akaname", name: "Akaname", file: "japanese-akaname.webp" },
      { id: "japanese-amazake-baba", name: "Amazake-Baba", file: "japanese-amazake-baba.webp" },
      { id: "japanese-ashiarai-yashiki", name: "Ashiarai Yashiki", file: "japanese-ashiarai-yashiki.webp" },
      { id: "japanese-azukiarai", name: "Azukiarai", file: "japanese-azukiarai.webp" },
      { id: "japanese-bake-kujira", name: "Bake-Kujira", file: "japanese-bake-kujira.webp" },
      { id: "japanese-bake-zori", name: "Bake-zori", file: "japanese-bake-zori.webp" },
      { id: "japanese-baku", name: "Baku", file: "japanese-baku.webp" },
      { id: "japanese-bunbuku-chagama", name: "Bunbuku Chagama", file: "japanese-bunbuku-chagama.webp" },
      { id: "japanese-chochin-obake", name: "Chochin-obake", file: "japanese-chochin-obake.webp" },
      { id: "japanese-hitotsume-kozo", name: "Hitotsume-kozo", file: "japanese-hitotsume-kozo.webp" },
      { id: "japanese-jinmenju", name: "Jinmenju", file: "japanese-jinmenju.webp" },
      { id: "japanese-kappa", name: "Kappa", file: "japanese-kappa.webp" },
      { id: "japanese-keukegen", name: "Keukegen", file: "japanese-keukegen.webp" },
      { id: "japanese-kitsune", name: "Kitsune", file: "japanese-kitsune.webp" },
      { id: "japanese-kotobuki", name: "Kotobuki", file: "japanese-kotobuki.webp" },
      { id: "japanese-mokumokuren", name: "Mokumokuren", file: "japanese-mokumokuren.webp" },
      { id: "japanese-namazu", name: "Namazu", file: "japanese-namazu.webp" },
      { id: "japanese-nurarihyon", name: "Nurarihyon", file: "japanese-nurarihyon.webp" },
      { id: "japanese-nurikabe", name: "Nurikabe", file: "japanese-nurikabe.webp" },
      { id: "japanese-omukade", name: "Omukade", file: "japanese-omukade.webp" },
      { id: "japanese-oni", name: "Oni", file: "japanese-oni.webp" },
      { id: "japanese-oni-hitokuchi", name: "Oni Hitokuchi", file: "japanese-oni-hitokuchi.webp" },
      { id: "japanese-ryomensukuna", name: "Ryomen Sukuna", file: "japanese-ryomensukuna.webp" },
      { id: "japanese-sarugami", name: "Sarugami", file: "japanese-sarugami.webp" },
      { id: "japanese-satori", name: "Satori", file: "japanese-satori.webp" },
      { id: "japanese-sazae-oni", name: "Sazae-oni", file: "japanese-sazae-oni.webp" },
      { id: "japanese-shikigami", name: "Shikigami", file: "japanese-shikigami.webp" },
      { id: "japanese-shirime", name: "Shirime", file: "japanese-shirime.webp" },
      { id: "japanese-shojo", name: "Shojo", file: "japanese-shojo.webp" },
      { id: "japanese-shuten-doji", name: "Shuten-dōji", file: "japanese-shuten-doji.webp" },
      { id: "japanese-tamamo-no-mae", name: "Tamamo-no-Mae", file: "japanese-tamamo-no-mae.webp" },
      { id: "japanese-tanuki", name: "Tanuki", file: "japanese-tanuki.webp" },
      { id: "japanese-tanukoro", name: "Tanukoro", file: "japanese-tanukoro.webp" },
      { id: "japanese-tengen", name: "Tengen", file: "japanese-tengen.webp" },
      { id: "japanese-tenjoname", name: "Tenjoname", file: "japanese-tenjoname.webp" },
      { id: "japanese-tofu-kozo", name: "Tofu-Kozo", file: "japanese-tofu-kozo.webp" },
      { id: "japanese-wanyudo", name: "Wanyudo", file: "japanese-wanyudo.webp" },
      { id: "japanese-yamata-no-orochi", name: "Yamata no Orochi", file: "japanese-yamata-no-orochi.webp" },
      { id: "japanese-yatagarasu", name: "Yatagarasu", file: "japanese-yatagarasu.webp" },
      { id: "japanese-yokai", name: "Yokai", file: "japanese-yokai.webp" },
      { id: "japanese-yuki-onna", name: "Yuki-onna", file: "japanese-yuki-onna.webp" },
    ]
  },
  {
    caput: "XI",
    title: "Egyptian Mythology",
    slug: "egyptian",
    divider: "assets/chapters/chapter-egyptian.webp",
    monsters: [
      { id: "egyptian-ammit", name: "Ammit", file: "egyptian-ammit.webp" },
      { id: "egyptian-amun", name: "Amun", file: "egyptian-amun.webp" },
      { id: "egyptian-anubi", name: "Anubis", file: "egyptian-anubi.webp" },
      { id: "egyptian-apophis", name: "Apophis", file: "egyptian-apophis.webp" },
      { id: "egyptian-atum", name: "Atum", file: "egyptian-atum.webp" },
      { id: "egyptian-bastet", name: "Bastet", file: "egyptian-bastet.webp" },
      { id: "egyptian-bes", name: "Bes", file: "egyptian-bes.webp" },
      { id: "egyptian-geb", name: "Geb", file: "egyptian-geb.webp" },
      { id: "egyptian-hathor", name: "Hathor", file: "egyptian-hathor.webp" },
      { id: "egyptian-horus", name: "Horus", file: "egyptian-horus.webp" },
      { id: "egyptian-isis", name: "Isis", file: "egyptian-isis.webp" },
      { id: "egyptian-khnum", name: "Khnum", file: "egyptian-khnum.webp" },
      { id: "egyptian-khonsu", name: "Khonsu", file: "egyptian-khonsu.webp" },
      { id: "egyptian-ma-at", name: "Ma'at", file: "egyptian-ma-at.webp" },
      { id: "egyptian-mut", name: "Mut", file: "egyptian-mut.webp" },
      { id: "egyptian-nephthys", name: "Nephthys", file: "egyptian-nephthys.webp" },
      { id: "egyptian-nun", name: "Nun", file: "egyptian-nun.webp" },
      { id: "egyptian-nut", name: "Nut", file: "egyptian-nut.webp" },
      { id: "egyptian-osiris", name: "Osiris", file: "egyptian-osiris.webp" },
      { id: "egyptian-ptah", name: "Ptah", file: "egyptian-ptah.webp" },
      { id: "egyptian-ra", name: "Ra", file: "egyptian-ra.webp" },
      { id: "egyptian-sekhmet", name: "Sekhmet", file: "egyptian-sekhmet.webp" },
      { id: "egyptian-serqet", name: "Serqet", file: "egyptian-serqet.webp" },
      { id: "egyptian-set", name: "Set", file: "egyptian-set.webp" },
      { id: "egyptian-shu", name: "Shu", file: "egyptian-shu.webp" },
      { id: "egyptian-sobek", name: "Sobek", file: "egyptian-sobek.webp" },
      { id: "egyptian-taweret", name: "Taweret", file: "egyptian-taweret.webp" },
      { id: "egyptian-tefnut", name: "Tefnut", file: "egyptian-tefnut.webp" },
      { id: "egyptian-thoth", name: "Thoth", file: "egyptian-thoth.webp" },
      { id: "egyptian-wadjet", name: "Wadjet", file: "egyptian-wadjet.webp" },
    ]
  },
  {
    caput: "XII",
    title: "Nordic Mythology",
    slug: "nordic",
    divider: "assets/chapters/chapter-nordic.webp",
    monsters: [
      { id: "nordic-aegir", name: "Aegir", file: "nordic-aegir.webp" },
      { id: "nordic-baldur", name: "Baldur", file: "nordic-baldur.webp" },
      { id: "nordic-bragi", name: "Bragi", file: "nordic-bragi.webp" },
      { id: "nordic-dagr", name: "Dagr", file: "nordic-dagr.webp" },
      { id: "nordic-eir", name: "Eir", file: "nordic-eir.webp" },
      { id: "nordic-freyja", name: "Freyja", file: "nordic-freyja.webp" },
      { id: "nordic-freyr", name: "Freyr", file: "nordic-freyr.webp" },
      { id: "nordic-frigg", name: "Frigg", file: "nordic-frigg.webp" },
      { id: "nordic-heimdall", name: "Heimdall", file: "nordic-heimdall.webp" },
      { id: "nordic-hel", name: "Hel", file: "nordic-hel.webp" },
      { id: "nordic-idunn", name: "Idunn", file: "nordic-idunn.webp" },
      { id: "nordic-loki", name: "Loki", file: "nordic-loki.webp" },
      { id: "nordic-mimir", name: "Mimir", file: "nordic-mimir.webp" },
      { id: "nordic-njord", name: "Njord", file: "nordic-njord.webp" },
      { id: "nordic-odin", name: "Odin", file: "nordic-odin.webp" },
      { id: "nordic-sif", name: "Sif", file: "nordic-sif.webp" },
      { id: "nordic-skadi", name: "Skadi", file: "nordic-skadi.webp" },
      { id: "nordic-thor", name: "Thor", file: "nordic-thor.webp" },
      { id: "nordic-tyr", name: "Tyr", file: "nordic-tyr.webp" },
      { id: "nordic-vidar", name: "Vidar", file: "nordic-vidar.webp" },
      { id: "nordic-andhrimnir", name: "Andhrímnir", file: "nordic-andhrimnir.webp" },
      { id: "nordic-audumbla", name: "Audumbla", file: "nordic-audumbla.webp" },
      { id: "nordic-buri", name: "Buri", file: "nordic-buri.webp" },
      { id: "nordic-fafnir", name: "Fafnir", file: "nordic-fafnir.webp" },
      { id: "nordic-fenrir", name: "Fenrir", file: "nordic-fenrir.webp" },
      { id: "nordic-huldra", name: "Huldra", file: "nordic-huldra.webp" },
      { id: "nordic-jormungandr", name: "Jörmungandr", file: "nordic-jormungandr.webp" },
      { id: "nordic-sleipnir", name: "Sleipnir", file: "nordic-sleipnir.webp" },
      { id: "nordic-valkyries", name: "Valkyries", file: "nordic-valkyries.webp" },
      { id: "nordic-ragnarok", name: "Ragnarök", file: "nordic-ragnarok.webp" },
      { id: "nordic-yggdrasil", name: "Yggdrasil", file: "nordic-yggdrasil.webp" },
    ]
  },
  {
    caput: "XIII",
    title: "Indian Mythology",
    slug: "indian",
    divider: "assets/chapters/chapter-indian.webp",
    monsters: [
      { id: "indian-agni", name: "Agni", file: "indian-agni.webp" },
      { id: "indian-brahma", name: "Brahma", file: "indian-brahma.webp" },
      { id: "indian-chandra", name: "Chandra", file: "indian-chandra.webp" },
      { id: "indian-durga-kali", name: "Durga & Kali", file: "indian-durga-kali.webp" },
      { id: "indian-ganesha", name: "Ganesha", file: "indian-ganesha.webp" },
      { id: "indian-garuda", name: "Garuda", file: "indian-garuda.webp" },
      { id: "indian-hanuman", name: "Hanuman", file: "indian-hanuman.webp" },
      { id: "indian-indra", name: "Indra", file: "indian-indra.webp" },
      { id: "indian-indrani", name: "Indrani", file: "indian-indrani.webp" },
      { id: "indian-kali", name: "Kali", file: "indian-kali.webp" },
      { id: "indian-kartikeya", name: "Kartikeya", file: "indian-kartikeya.webp" },
      { id: "indian-kubera", name: "Kubera", file: "indian-kubera.webp" },
      { id: "indian-lakshmi", name: "Lakshmi", file: "indian-lakshmi.webp" },
      { id: "indian-makara", name: "Makara", file: "indian-makara.webp" },
      { id: "indian-naga", name: "Naga", file: "indian-naga.webp" },
      { id: "indian-parvati", name: "Parvati", file: "indian-parvati.webp" },
      { id: "indian-rakshasa", name: "Rakshasa", file: "indian-rakshasa.webp" },
      { id: "indian-rama", name: "Rama", file: "indian-rama.webp" },
      { id: "indian-sarasvati", name: "Sarasvati", file: "indian-sarasvati.webp" },
      { id: "indian-saraswatis-hamsa", name: "Saraswati's Hamsa", file: "indian-saraswatis-hamsa.webp" },
      { id: "indian-sharabha", name: "Sharabha", file: "indian-sharabha.webp" },
      { id: "indian-shiva", name: "Shiva", file: "indian-shiva.webp" },
      { id: "indian-surya", name: "Surya", file: "indian-surya.webp" },
      { id: "indian-vayu", name: "Vayu", file: "indian-vayu.webp" },
      { id: "indian-vishnu", name: "Vishnu", file: "indian-vishnu.webp" },
      { id: "indian-yakshini", name: "Yakshini", file: "indian-yakshini.webp" },
      { id: "indian-yama", name: "Yama", file: "indian-yama.webp" },
    ]
  },
  {
    caput: "XIV",
    title: "Slavic Folklore",
    slug: "slavic",
    divider: "assets/chapters/chapter-slavic.webp",
    monsters: [
      { id: "slavic-alkonost", name: "Alkonost", file: "slavic-alkonost.webp" },
      { id: "slavic-aspid", name: "Aspid", file: "slavic-aspid.webp" },
      { id: "slavic-baba-yaga", name: "Baba Yaga", file: "slavic-baba-yaga.webp" },
      { id: "slavic-bannik", name: "Bannik", file: "slavic-bannik.webp" },
      { id: "slavic-chort", name: "Chort", file: "slavic-chort.webp" },
      { id: "slavic-domovoi", name: "Domovoi", file: "slavic-domovoi.webp" },
      { id: "slavic-drekavac", name: "Drekavac", file: "slavic-drekavac.webp" },
      { id: "slavic-gamayun", name: "Gamayun", file: "slavic-gamayun.webp" },
      { id: "slavic-kikimora", name: "Kikimora", file: "slavic-kikimora.webp" },
      { id: "slavic-koschei", name: "Koschei the Deathless", file: "slavic-koschei.webp" },
      { id: "slavic-leshy", name: "Leshy", file: "slavic-leshy.webp" },
      { id: "slavic-lihoradka", name: "Lihoradka", file: "slavic-lihoradka.webp" },
      { id: "slavic-likho", name: "Likho", file: "slavic-likho.webp" },
      { id: "slavic-ovinnik", name: "Ovinnik", file: "slavic-ovinnik.webp" },
      { id: "slavic-polevik", name: "Polevik", file: "slavic-polevik.webp" },
      { id: "slavic-poludnitsa", name: "Poludnitsa", file: "slavic-poludnitsa.webp" },
      { id: "slavic-psoglav", name: "Psoglav", file: "slavic-psoglav.webp" },
      { id: "slavic-rusalka", name: "Rusalka", file: "slavic-rusalka.webp" },
      { id: "slavic-sirin", name: "Sirin", file: "slavic-sirin.webp" },
      { id: "slavic-strzyga", name: "Strzyga", file: "slavic-strzyga.webp" },
      { id: "slavic-tuburni", name: "Tuburni", file: "slavic-tuburni.webp" },
      { id: "slavic-upyr", name: "Upyr", file: "slavic-upyr.webp" },
      { id: "slavic-vila", name: "Vila", file: "slavic-vila.webp" },
      { id: "slavic-vodnik", name: "Vodník", file: "slavic-vodnik.webp" },
      { id: "slavic-vodyanoy", name: "Vodyanoy", file: "slavic-vodyanoy.webp" },
      { id: "slavic-volkodlak", name: "Volkodlak", file: "slavic-volkodlak.webp" },
      { id: "slavic-zduhac", name: "Zduhac", file: "slavic-zduhac.webp" },
      { id: "slavic-zhar-ptitsa", name: "Zhar-Ptitsa", file: "slavic-zhar-ptitsa.webp" },
      { id: "slavic-zmey", name: "Zmey", file: "slavic-zmey.webp" },
    ]
  },
  {
    caput: "XV",
    title: "Miscellanea",
    slug: "miscellaneous",
    divider: "assets/chapters/chapter-miscellaneous.webp",
    monsters: [
      { id: "miscellaneous-adze", name: "Adze", file: "miscellaneous-adze.webp" },
      { id: "miscellaneous-ahool", name: "Ahool", file: "miscellaneous-ahool.webp" },
      { id: "miscellaneous-ahuizotl", name: "Ahuizotl", file: "miscellaneous-ahuizotl.webp" },
      { id: "miscellaneous-akkorokamui", name: "Akkorokamui", file: "miscellaneous-akkorokamui.webp" },
      { id: "miscellaneous-amarok", name: "Amarok", file: "miscellaneous-amarok.webp" },
      { id: "miscellaneous-amphisbaena", name: "Amphisbaena", file: "miscellaneous-amphisbaena.webp" },
      { id: "miscellaneous-annunaki", name: "Annunaki", file: "miscellaneous-annunaki.webp" },
      { id: "miscellaneous-aqrabuamelu", name: "Aqrabuamelu", file: "miscellaneous-aqrabuamelu.webp" },
      { id: "miscellaneous-aswang", name: "Aswang", file: "miscellaneous-aswang.webp" },
      { id: "miscellaneous-aurelioren", name: "Aureliorën", file: "miscellaneous-aurelioren.webp" },
      { id: "miscellaneous-azeban", name: "Azeban", file: "miscellaneous-azeban.webp" },
      { id: "miscellaneous-baal", name: "Baal", file: "miscellaneous-baal.webp" },
      { id: "miscellaneous-badb", name: "Badb", file: "miscellaneous-badb.webp" },
      { id: "miscellaneous-banshee", name: "Banshee", file: "miscellaneous-banshee.webp" },
      { id: "miscellaneous-barghest", name: "Barghest", file: "miscellaneous-barghest.webp" },
      { id: "miscellaneous-basilisk", name: "Basilisk", file: "miscellaneous-basilisk.webp" },
      { id: "miscellaneous-beast-of-gevaudan", name: "Beast of Gévaudan", file: "miscellaneous-beast-of-gevaudan.webp" },
      { id: "miscellaneous-black-annis", name: "Black Annis", file: "miscellaneous-black-annis.webp" },
      { id: "miscellaneous-bonnacon", name: "Bonnacon", file: "miscellaneous-bonnacon.webp" },
      { id: "miscellaneous-buer", name: "Buer", file: "miscellaneous-buer.webp" },
      { id: "miscellaneous-bunyip", name: "Bunyip", file: "miscellaneous-bunyip.webp" },
      { id: "miscellaneous-cadejo", name: "Cadejo", file: "miscellaneous-cadejo.webp" },
      { id: "miscellaneous-chupacabra", name: "Chupacabra", file: "miscellaneous-chupacabra.webp" },
      { id: "miscellaneous-cinnamon-bird", name: "Cinnamon Bird", file: "miscellaneous-cinnamon-bird.webp" },
      { id: "miscellaneous-cockatrice", name: "Cockatrice", file: "miscellaneous-cockatrice.webp" },
      { id: "miscellaneous-doppelganger", name: "Doppelgänger", file: "miscellaneous-doppelganger.webp" },
      { id: "miscellaneous-dwarfs", name: "Dwarfs", file: "miscellaneous-dwarfs.webp" },
      { id: "miscellaneous-encantado", name: "Encantado", file: "miscellaneous-encantado.webp" },
      { id: "miscellaneous-faun", name: "Faun", file: "miscellaneous-faun.webp" },
      { id: "miscellaneous-gancanagh", name: "Gancanagh", file: "miscellaneous-gancanagh.webp" },
      { id: "miscellaneous-ghoul", name: "Ghoul", file: "miscellaneous-ghoul.webp" },
      { id: "miscellaneous-gnomus-silvarum", name: "Gnomus Silvarum", file: "miscellaneous-gnomus-silvarum.webp" },
      { id: "miscellaneous-goblins", name: "Goblins", file: "miscellaneous-goblins.webp" },
      { id: "miscellaneous-golem", name: "Golem", file: "miscellaneous-golem.webp" },
      { id: "miscellaneous-grootslang", name: "Grootslang", file: "miscellaneous-grootslang.webp" },
      { id: "miscellaneous-gryphus", name: "Gryphus", file: "miscellaneous-gryphus.webp" },
      { id: "miscellaneous-hidebehind", name: "Hidebehind", file: "miscellaneous-hidebehind.webp" },
      { id: "miscellaneous-hodag", name: "Hodag", file: "miscellaneous-hodag.webp" },
      { id: "miscellaneous-hoop-snake", name: "Hoop Snake", file: "miscellaneous-hoop-snake.webp" },
      { id: "miscellaneous-ittan-momen", name: "Ittan-momen", file: "miscellaneous-ittan-momen.webp" },
      { id: "miscellaneous-jackalope", name: "Jackalope", file: "miscellaneous-jackalope.webp" },
      { id: "miscellaneous-jersey-devil", name: "Jersey Devil", file: "miscellaneous-jersey-devil.webp" },
      { id: "miscellaneous-jingwei", name: "Jingwei", file: "miscellaneous-jingwei.webp" },
      { id: "miscellaneous-jokernox", name: "Jokernox", file: "miscellaneous-jokernox.webp" },
      { id: "miscellaneous-keelut", name: "Keelut", file: "miscellaneous-keelut.webp" },
      { id: "miscellaneous-kelpie", name: "Kelpie", file: "miscellaneous-kelpie.webp" },
      { id: "miscellaneous-kishi", name: "Kishi", file: "miscellaneous-kishi.webp" },
      { id: "miscellaneous-kumiho", name: "Kumiho", file: "miscellaneous-kumiho.webp" },
      { id: "miscellaneous-leprechaun", name: "Leprechaun", file: "miscellaneous-leprechaun.webp" },
      { id: "miscellaneous-leviathan", name: "Leviathan", file: "miscellaneous-leviathan.webp" },
      { id: "miscellaneous-long", name: "Long", file: "miscellaneous-long.webp" },
      { id: "miscellaneous-luminae", name: "Luminae", file: "miscellaneous-luminae.webp" },
      { id: "miscellaneous-mahaha", name: "Mahaha", file: "miscellaneous-mahaha.webp" },
      { id: "miscellaneous-mapinguari", name: "Mapinguari", file: "miscellaneous-mapinguari.webp" },
      { id: "miscellaneous-mimic", name: "Mimic", file: "miscellaneous-mimic.webp" },
      { id: "miscellaneous-mngwa", name: "Mngwa", file: "miscellaneous-mngwa.webp" },
      { id: "miscellaneous-moon-rabbit", name: "Moon Rabbit", file: "miscellaneous-moon-rabbit.webp" },
      { id: "miscellaneous-nuckelavee", name: "Nuckelavee", file: "miscellaneous-nuckelavee.webp" },
      { id: "miscellaneous-olgoi-khorkhoi", name: "Olgoi-Khorkhoi", file: "miscellaneous-olgoi-khorkhoi.webp" },
      { id: "miscellaneous-onocentaur", name: "Onocentaur", file: "miscellaneous-onocentaur.webp" },
      { id: "miscellaneous-ouroboros", name: "Ouroboros", file: "miscellaneous-ouroboros.webp" },
      { id: "miscellaneous-owlman", name: "Owlman", file: "miscellaneous-owlman.webp" },
      { id: "miscellaneous-pazuzu", name: "Pazuzu", file: "miscellaneous-pazuzu.webp" },
      { id: "miscellaneous-peluda", name: "Peluda", file: "miscellaneous-peluda.webp" },
      { id: "miscellaneous-pollo-maligno", name: "Pollo Maligno", file: "miscellaneous-pollo-maligno.webp" },
      { id: "miscellaneous-pope-lick-monster", name: "Pope Lick Monster", file: "miscellaneous-pope-lick-monster.webp" },
      { id: "miscellaneous-pukwudgie", name: "Pukwudgie", file: "miscellaneous-pukwudgie.webp" },
      { id: "miscellaneous-qalupalik", name: "Qalupalik", file: "miscellaneous-qalupalik.webp" },
      { id: "miscellaneous-questing-beast", name: "Questing Beast", file: "miscellaneous-questing-beast.webp" },
      { id: "miscellaneous-ratatoskr", name: "Ratatoskr", file: "miscellaneous-ratatoskr.webp" },
      { id: "miscellaneous-roc", name: "Roc", file: "miscellaneous-roc.webp" },
      { id: "miscellaneous-sandman", name: "Sandman", file: "miscellaneous-sandman.webp" },
      { id: "miscellaneous-shahmaran", name: "Shahmaran", file: "miscellaneous-shahmaran.webp" },
      { id: "miscellaneous-shapeshifter", name: "Shapeshifter", file: "miscellaneous-shapeshifter.webp" },
      { id: "miscellaneous-sheep-eating-tree", name: "Sheep-Eating Tree", file: "miscellaneous-sheep-eating-tree.webp" },
      { id: "miscellaneous-sigbin", name: "Sigbin", file: "miscellaneous-sigbin.webp" },
      { id: "miscellaneous-skinwalker", name: "Skinwalker", file: "miscellaneous-skinwalker.webp" },
      { id: "miscellaneous-squonk", name: "Squonk", file: "miscellaneous-squonk.webp" },
      { id: "miscellaneous-sun-wukong", name: "Sun Wukong", file: "miscellaneous-sun-wukong.webp" },
      { id: "miscellaneous-tarasque", name: "Tarasque", file: "miscellaneous-tarasque.webp" },
      { id: "miscellaneous-tatzelwurm", name: "Tatzelwurm", file: "miscellaneous-tatzelwurm.webp" },
      { id: "miscellaneous-teju-jagua", name: "Teju Jagua", file: "miscellaneous-teju-jagua.webp" },
      { id: "miscellaneous-dragon-king", name: "The Dragon King", file: "miscellaneous-dragon-king.webp" },
      { id: "miscellaneous-apocalyps-riders", name: "The Four Riders of the Apocalypse", file: "miscellaneous-apocalyps-riders.webp" },
      { id: "miscellaneous-tiamat", name: "Tiamat", file: "miscellaneous-tiamat.webp" },
      { id: "miscellaneous-tilberi", name: "Tilberi", file: "miscellaneous-tilberi.webp" },
      { id: "miscellaneous-trauco", name: "Trauco", file: "miscellaneous-trauco.webp" },
      { id: "miscellaneous-troll", name: "Troll", file: "miscellaneous-troll.webp" },
      { id: "miscellaneous-unicorn", name: "Unicorn", file: "miscellaneous-unicorn.webp" },
      { id: "miscellaneous-vanara", name: "Vanara", file: "miscellaneous-vanara.webp" },
      { id: "miscellaneous-vegetable-lamb-of-tartary", name: "Vegetable Lamb of Tartary", file: "miscellaneous-vegetable-lamb-of-tartary.webp" },
      { id: "miscellaneous-wampus-cat", name: "Wampus Cat", file: "miscellaneous-wampus-cat.webp" },
      { id: "miscellaneous-wendigo", name: "Wendigo", file: "miscellaneous-wendigo.webp" },
      { id: "miscellaneous-will-o-the-wisp", name: "Will-o'-the-Wisp", file: "miscellaneous-will-o-the-wisp.webp" },
      { id: "miscellaneous-wisakedjak", name: "Wisakedjak", file: "miscellaneous-wisakedjak.webp" },
      { id: "miscellaneous-wolpertinger", name: "Wolpertinger", file: "miscellaneous-wolpertinger.webp" },
      { id: "miscellaneous-wuchowsen", name: "Wuchowsen", file: "miscellaneous-wuchowsen.webp" },
      { id: "miscellaneous-yara-ma-yha-who", name: "Yara-ma-yha-who", file: "miscellaneous-yara-ma-yha-who.webp" },
    ]
  },
  {
    caput: "XVI",
    title: "Anime & Cartoons",
    slug: "anime",
    divider: "assets/chapters/chapter-anime.webp",
    monsters: [
      { id: "anime-finnian-of-ooo", name: "Finnian of Ooo", file: "anime-finnian-of-ooo.webp" },
      { id: "anime-jake-the-dog", name: "Jake the Dog", file: "anime-jake-the-dog.webp" },
      { id: "anime-princess-bubblegum", name: "Princess Bubblegum", file: "anime-princess-bubblegum.webp" },
      { id: "anime-marceline", name: "Marceline", file: "anime-marceline.webp" },
      { id: "anime-bmo", name: "BMO", file: "anime-bmo.webp" },
      { id: "anime-gunter", name: "Gunter", file: "anime-gunter.webp" },
      { id: "anime-alismera", name: "Alismera", file: "anime-alismera.webp" },
      { id: "anime-caeluror", name: "Caeluror", file: "anime-caeluror.webp" },
      { id: "anime-madhattereon", name: "Madhattereon", file: "anime-madhattereon.webp" },
      { id: "anime-asterix-obelix", name: "Asterix & Obelix", file: "anime-asterix-obelix.webp" },
      { id: "anime-levi-ackerman", name: "Levi Ackerman", file: "anime-levi-ackerman.webp" },
      { id: "anime-guts", name: "Guts", file: "anime-guts.webp" },
      { id: "anime-chaliceus", name: "Chaliceus", file: "anime-chaliceus.webp" },
      { id: "anime-the-devil", name: "The Devil", file: "anime-the-devil.webp" },
      { id: "anime-king-dice", name: "King Dice", file: "anime-king-dice.webp" },
      { id: "anime-turbo-granny", name: "Turbo Granny", file: "anime-turbo-granny.webp" },
      { id: "anime-ryuk", name: "Ryuk", file: "anime-ryuk.webp" },
      { id: "anime-dora-the-explorer", name: "Dora the Explorer", file: "anime-dora-the-explorer.webp" },
      { id: "anime-goku", name: "Goku", file: "anime-goku.webp" },
      { id: "anime-vegeta", name: "Vegeta", file: "anime-vegeta.webp" },
      { id: "anime-master-roshi", name: "Master Roshi", file: "anime-master-roshi.webp" },
      { id: "anime-lyrenae", name: "Lyrenae", file: "anime-lyrenae.webp" },
      { id: "anime-natsu-dragneel", name: "Natsu Dragneel", file: "anime-natsu-dragneel.webp" },
      { id: "anime-happy", name: "Happy", file: "anime-happy.webp" },
      { id: "anime-frieren", name: "Frieren", file: "anime-frieren.webp" },
      { id: "anime-frieren-zoltraak", name: "Frieren: Zoltraak", file: "anime-frieren-zoltraak.webp" },
      { id: "anime-frieren-flower-field", name: "Frieren: Flower Field", file: "anime-frieren-flower-field.webp" },
      { id: "anime-elric", name: "Elric", file: "anime-elric.webp" },
      { id: "anime-bill-cypher", name: "Bill Cypher", file: "anime-bill-cypher.webp" },
      { id: "anime-hello-kitty-and-friends", name: "Hello Kitty and Friends", file: "anime-hello-kitty-and-friends.webp" },
      { id: "anime-kuromi", name: "Kuromi", file: "anime-kuromi.webp" },
      { id: "anime-alucard", name: "Alucard", file: "anime-alucard.webp" },
      { id: "anime-hollow-knight", name: "Hollow Knight", file: "anime-hollow-knight.webp" },
      { id: "anime-hornet", name: "Hornet", file: "anime-hornet.webp" },
      { id: "anime-hisoka", name: "Hisoka", file: "anime-hisoka.webp" },
      { id: "anime-yuji-itadori", name: "Yuji Itadori", file: "anime-yuji-itadori.webp" },
      { id: "anime-gojo", name: "Gojo", file: "anime-gojo.webp" },
      { id: "anime-megumi", name: "Megumi", file: "anime-megumi.webp" },
      { id: "anime-geto", name: "Geto", file: "anime-geto.webp" },
      { id: "anime-yuta-okkotsu", name: "Yuta Okkotsu", file: "anime-yuta-okkotsu.webp" },
      { id: "anime-malevolent-shrine", name: "Malevolent Shrine", file: "anime-malevolent-shrine.webp" },
      { id: "anime-sora", name: "Sora", file: "anime-sora.webp" },
      { id: "anime-kirbalos", name: "Kirbalos", file: "anime-kirbalos.webp" },
      { id: "anime-link", name: "Link", file: "anime-link.webp" },
      { id: "anime-hylian-aurelith", name: "Hylian Aurelith", file: "anime-hylian-aurelith.webp" },
      { id: "anime-bugs-and-lola", name: "Bugs & Lola", file: "anime-bugs-and-lola.webp" },
      { id: "anime-reigenesis", name: "Reigenesis", file: "anime-reigenesis.webp" },
      { id: "anime-naruto", name: "Naruto", file: "anime-naruto.webp" },
      { id: "anime-sasuke", name: "Sasuke", file: "anime-sasuke.webp" },
      { id: "anime-pain", name: "Pain", file: "anime-pain.webp" },
      { id: "anime-monkey-d-luffy", name: "Monkey D. Luffy", file: "anime-monkey-d-luffy.webp" },
      { id: "anime-roronoa-zoro", name: "Roronoa Zoro", file: "anime-roronoa-zoro.webp" },
      { id: "anime-nami", name: "Nami", file: "anime-nami.webp" },
      { id: "anime-usopp", name: "Usopp", file: "anime-usopp.webp" },
      { id: "anime-sanji", name: "Sanji", file: "anime-sanji.webp" },
      { id: "anime-tony-tony-chopper", name: "Tony Tony Chopper", file: "anime-tony-tony-chopper.webp" },
      { id: "anime-nico-robin", name: "Nico Robin", file: "anime-nico-robin.webp" },
      { id: "anime-franky", name: "Franky", file: "anime-franky.webp" },
      { id: "anime-brook", name: "Brook", file: "anime-brook.webp" },
      { id: "anime-jinbe", name: "Jinbe", file: "anime-jinbe.webp" },
      { id: "anime-boa-hancock", name: "Boa Hancock", file: "anime-boa-hancock.webp" },
      { id: "anime-donquixote-rosinante", name: "Donquixote Rosinante", file: "anime-donquixote-rosinante.webp" },
      { id: "anime-nika", name: "Nika", file: "anime-nika.webp" },
      { id: "anime-perry-the-platypus", name: "Perry the Platypus", file: "anime-perry-the-platypus.webp" },
      { id: "anime-pingu", name: "Pingu", file: "anime-pingu.webp" },
      { id: "anime-joculator-rex", name: "Joculator Rex", file: "anime-joculator-rex.webp" },
      { id: "anime-pupillo", name: "Pupillo", file: "anime-pupillo.webp" },
      { id: "anime-coda-and-verdicci", name: "Coda & Verdicci", file: "anime-coda-and-verdicci.webp" },
      { id: "anime-jiminy", name: "Jiminy", file: "anime-jiminy.webp" },
      { id: "anime-pikachu", name: "Pikachu", file: "anime-pikachu.webp" },
      { id: "anime-bulbasaur", name: "Bulbasaur", file: "anime-bulbasaur.webp" },
      { id: "anime-charmander", name: "Charmander", file: "anime-charmander.webp" },
      { id: "anime-charizard", name: "Charizard", file: "anime-charizard.webp" },
      { id: "anime-squirtle", name: "Squirtle", file: "anime-squirtle.webp" },
      { id: "anime-psyduck", name: "Psyduck", file: "anime-psyduck.webp" },
      { id: "anime-gengar", name: "Gengar", file: "anime-gengar.webp" },
      { id: "anime-pumuckl", name: "Pumuckl", file: "anime-pumuckl.webp" },
      { id: "anime-noctivar", name: "Noctivar", file: "anime-noctivar.webp" },
      { id: "anime-poppicus", name: "Poppicus", file: "anime-poppicus.webp" },
      { id: "anime-lunatarii", name: "Lunatarii", file: "anime-lunatarii.webp" },
      { id: "anime-rayman", name: "Rayman", file: "anime-rayman.webp" },
      { id: "anime-cartman", name: "Cartman", file: "anime-cartman.webp" },
      { id: "anime-kenny", name: "Kenny", file: "anime-kenny.webp" },
      { id: "anime-kyle", name: "Kyle", file: "anime-kyle.webp" },
      { id: "anime-stan", name: "Stan", file: "anime-stan.webp" },
      { id: "anime-asmongold", name: "Asmongold", file: "anime-asmongold.webp" },
      { id: "anime-totoro", name: "Totoro", file: "anime-totoro.webp" },
      { id: "anime-no-face", name: "No-Face", file: "anime-no-face.webp" },
      { id: "anime-jack-skellington-and-sally", name: "Jack Skellington & Sally", file: "anime-jack-skellington-and-sally.webp" },
      { id: "anime-geralt-and-yennefer", name: "Geralt von Riva & Jennifer von Vennenberg", file: "anime-geralt-and-yennefer.webp" },
      { id: "anime-dr-mortivus", name: "Dr. Mortivus of Hollow Frames", file: "anime-dr-mortivus.webp" },
      { id: "anime-tom-and-jerry", name: "Tom & Jerry", file: "anime-tom-and-jerry.webp" },
      { id: "anime-tomie", name: "Tomie", file: "anime-tomie.webp" },
    ]
  },
  {
    caput: "XVII",
    title: "Zodiac Signs",
    slug: "zodiac",
    divider: "assets/chapters/chapter-zodiac.webp",
    monsters: [
      { id: "zodiac-aries", name: "Aries", file: "zodiac-aries.webp" },
      { id: "zodiac-taurus", name: "Taurus", file: "zodiac-taurus.webp" },
      { id: "zodiac-gemini", name: "Gemini", file: "zodiac-gemini.webp" },
      { id: "zodiac-cancer", name: "Cancer", file: "zodiac-cancer.webp" },
      { id: "zodiac-leo", name: "Leo", file: "zodiac-leo.webp" },
      { id: "zodiac-virgo", name: "Virgo", file: "zodiac-virgo.webp" },
      { id: "zodiac-libra", name: "Libra", file: "zodiac-libra.webp" },
      { id: "zodiac-scorpio", name: "Scorpio", file: "zodiac-scorpio.webp" },
      { id: "zodiac-sagittarius", name: "Sagittarius", file: "zodiac-sagittarius.webp" },
      { id: "zodiac-capricorn", name: "Capricorn", file: "zodiac-capricorn.webp" },
      { id: "zodiac-aquarius", name: "Aquarius", file: "zodiac-aquarius.webp" },
      { id: "zodiac-pisces", name: "Pisces", file: "zodiac-pisces.webp" },
    ]
  },
  {
    caput: "XVIII",
    title: "Chinese Zodiac",
    slug: "chinese-zodiac",
    divider: "assets/chapters/chapter-chinese-zodiac.webp",
    monsters: [
      { id: "chinese-zodiac-zilongshu", name: "Zilongshu", file: "cz-zilongshu.webp" },
      { id: "chinese-zodiac-niuwei", name: "Niuwei", file: "cz-niuwei.webp" },
      { id: "chinese-zodiac-huyin", name: "Huyin", file: "cz-huyin.webp" },
      { id: "chinese-zodiac-yue-tu", name: "Yùe-Tù", file: "cz-yue-tu.webp" },
      { id: "chinese-zodiac-longwei", name: "Longwei", file: "cz-longwei.webp" },
      { id: "chinese-zodiac-sulyan", name: "Sulyan", file: "cz-sulyan.webp" },
      { id: "chinese-zodiac-xianglian", name: "Xianglian", file: "cz-xianglian.webp" },
      { id: "chinese-zodiac-yanglu", name: "Yánglù", file: "cz-yanglu.webp" },
      { id: "chinese-zodiac-houlin", name: "Hóulín", file: "cz-houlin.webp" },
      { id: "chinese-zodiac-canis-veritatis", name: "Canis Veritatis", file: "cz-canis-veritatis.webp" },
      { id: "chinese-zodiac-zhuru", name: "Zhurù", file: "cz-zhuru.webp" },
    ]
  }
];

// Flatten to the legacy MONSTERS array. Each plate carries its chapter
// index (for any code that still references it).
const MONSTERS = CHAPTERS.flatMap((ch, ci) =>
  ch.monsters.map(m => ({ ...m, chapter: ci }))
);
